quest event api draft
terrarium-earth/hercules pull request #104
Opened 2023-10-17 06:33 UTC by finasera

- Extract QuestEntry
- Add unstable Quest Events API

2023-10-17 07:57 UTC, sisby-folk reviewed
Take our non-maintainer opinions with a grain of salt, but you're welcome to them anyway

2023-10-17 07:57 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/events/QuestEvent.java
> + */
I think these can be skipped considering the self-documenting names and annotation

2023-10-17 07:57 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/events/QuestEvents.java
> +    private static final Event<Completed> COMPLETED = EventFactory.createLoop();
If this is private, there's no way to uh, actually subscribe to it.

2023-10-17 07:57 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/events/QuestEvents.java
> +    }
I reckon you can drop this lot, calling the invoker directly is pretty conventional

2023-10-17 07:57 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/events/QuestEvent.java
> +        return new QuestEvent(entry.id(), player.getUUID());
Why not just use `ResourceLocation id, Quest quest, ServerPlayer player`? The data is already available, there's no reason to squash it and force API consumers to need to look it all up again.

2023-10-17 07:57 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/common/handlers/progress/QuestsProgress.java
> +        NetworkHandler.CHANNEL.sendToPlayer(new QuestCompletedPacket(entry.id()), player);
This should be a listener registered to `QuestEvents.COMPLETED` instead of being hardcoded in-place. Even just as proof of function.

2023-10-17 08:03 UTC, finasera commented on common/src/main/java/earth/terrarium/heracles/api/events/QuestEvents.java
> +    private static final Event<Completed> COMPLETED = EventFactory.createLoop();
…Looks like I forgot to add a registration hook. Given the below feedback, I'll just make this public.

2023-10-17 20:00 UTC, ThatGravyBoat commented
Hello, you seemed to of used Architectury API we do not use that in our projects the reason you can use it is because of our REI compat you can copy how we do events in our other mods here https://github.com/terrarium-earth/Prometheus/blob/1.20.x/common/src/main/java/earth/terrarium/prometheus/api/events/MemberRolesChangedEvent.java

2023-10-19 13:07 UTC, ThatGravyBoat requested changes

2023-10-19 13:07 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/events/HeraclesEvents.java
> +    static final List<QuestCompleteListener> QUEST_PROGRESS = new ArrayList<>();
these can be set to private

2023-10-19 13:07 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/events/HeraclesEvents.java
> +    static {
I would perfer if this was moved to the mod init method instead to keep API semi separated from usage

2023-10-19 13:07 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/common/handlers/progress/TaskProgress.java
> +import earth.terrarium.heracles.api.events.HeraclesEvents;
These seem to be left overs

2023-10-20 17:13 UTC, ThatGravyBoat approved these changes

2023-10-20 17:14 UTC, merged

2023-10-20 17:51 UTC, finasera commented
Thanks for the review!