Add toast wrapping
terrarium-earth/hercules pull request #105
Opened 2023-10-17 10:54 UTC by sisby-folk

Adds a nice common component capable of wrapping text, showing hints half way through toast duration, and so on. 

Used for quest complete and quest update right now.

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/be73fcde-ce49-4ad5-b6ce-f6bae7f88a06)
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/31dd86ec-970f-4bd0-b720-6b4637cb3486)
![javaw_obuQLkrLhj](https://github.com/terrarium-earth/Heracles/assets/55819817/6dae5288-5618-4f0a-a817-4b4a13a606ae)

2023-10-17 11:27 UTC, ThatGravyBoat requested changes

2023-10-17 11:27 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/toasts/WrappingHintToast.java
> +        graphics.blit(TEXTURE, 0, 0, 0, 0, width(), 16);
This can be done using `blitNineSliced` which should make it resize to anything.

2023-10-18 00:32 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/toasts/WrappingHintToast.java
> +        graphics.blit(TEXTURE, 0, 0, 0, 0, width(), 16);
done up in c781981 - i also shifted the purple color used up two shades to improve legibility:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/613ef525-1c47-47fe-aba4-5071f2483f7b)

2023-10-19 05:25 UTC, ThatGravyBoat approved these changes

2023-10-19 05:25 UTC, merged