Item Modals: Unleashed Edition
terrarium-earth/hercules pull request #122
Opened 2023-10-25 06:04 UTC by sisby-folk

## Featuring:

**Namespace tooltips with searching (fixes `#minecraft:pickaxes` and `#c:pickaxes` being indistinguishable)**

![javaw_hUUp8CV6mp](https://github.com/terrarium-earth/Heracles/assets/55819817/0b63c8d3-6732-4d72-9370-22e2c7f1f935)
![javaw_nVh3jnLhhQ](https://github.com/terrarium-earth/Heracles/assets/55819817/2f3cfef3-86b0-4b39-93de-c746cd33ca4f)
![javaw_HvvPTjEx5e](https://github.com/terrarium-earth/Heracles/assets/55819817/e603fb29-f8c2-4d05-b1a7-e5e1029eee51)
![javaw_CjbEoc3ATA](https://github.com/terrarium-earth/Heracles/assets/55819817/a7663d82-6564-4dfa-a00a-ddd6c473b470)

This uses platform-specific implementations for getting mod titles, so we had to fix an issue in the buildscript that broke those.

---

**Replacing IconModal and ItemQuestIcon(Item) with ItemModal and ItemQuestIcon(ItemModal.Value)**

https://github.com/terrarium-earth/Heracles/assets/55819817/9dc44130-0793-4ba9-afa1-0924365c0cd1

https://github.com/terrarium-earth/Heracles/assets/55819817/9d55d044-56f7-4e9e-8f5a-a0d0bd261107

![javaw_bOwK1g2GML](https://github.com/terrarium-earth/Heracles/assets/55819817/c6346eec-258b-4970-a98b-2f3b15f87ccb)

ItemModal.Value seemed very useful and very related to RegistryValue<Item>, so I made it into a class called ItemValue that extends RegistryValue<Item> instead. It can similarly represent an itemstack (with nbt), a tag, or an item.

*The inheritence is a bit messy as RegistryValue was never really designed for this, so that could be improved in the future.*

---

Also fixed a crash and made it so that item task icons show their NBT (for, for example - this potion task! which showed a water bottle before, and only said `Potion` in the title)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/c327175f-4238-468f-b574-fe25b0c2355f)

The good news is - Our current quests still work great! which would imply there aren't any legacy codec parsing issues.

2023-10-26 11:26 UTC, ThatGravyBoat requested changes

2023-10-26 11:26 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/common/utils/ItemValue.java
> +        this(item, item.map(
I think these should be lazy loaded instead of loaded on class creation now since its used in normal just the modal.

2023-10-26 11:26 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/common/utils/PlatformUtils.java
> +    public static String guessModTitle(String namespace) {
This does not need to be expect platform, I in Resourceful Lib provide a crossplatform mod info utility so you can change it to the following:
```suggestion
    public static String guessModTitle(String namespace) {
        Optional<ModInfo> info = Optional.ofNullable(ModInfoUtils.getModInfo(namespace))
            .or(() -> Optional.ofNullable(ModInfoUtils.getModInfo(namespace.replace("_", "-"))));
        if (info.isPresent()) {
            return info.get().displayName();
        }
        String prettifiedNamespace = StringUtils.capitalize(namespace.replace("_", " ").replace("/", " 🡲 "));
        if (prettifiedNamespace.equals("C")) prettifiedNamespace = "Common";
        return prettifiedNamespace;
    }
    ```
    This would also mean that you can remove the dependency on arch expect platform again.

2023-10-26 11:26 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/ItemTaskWidget.java
> +                ItemStack stack = item.getDefaultInstance();
getDefaultInstance should either copy or this should copy.

2023-10-26 11:26 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/ItemInteractTaskWidget.java
> +                    ItemStack stack = item.getDefaultInstance();
See comment in ItemTaskWidget

2023-10-26 11:26 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/common/utils/RegistryValue.java
> +public class RegistryValue<T> {
seal this class and permit ItemValue only

2023-10-26 23:50 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/ItemTaskWidget.java
> +                ItemStack stack = item.getDefaultInstance();
getDefaultInstance uses the ItemLike stack constructor, so it's a new copy every time afaik.

2023-10-26 23:50 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/ItemInteractTaskWidget.java
> +                    ItemStack stack = item.getDefaultInstance();
See reply in ItemTaskWidget

2023-10-26 23:58 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/ItemTaskWidget.java
> +                ItemStack stack = item.getDefaultInstance();
my bad I thought it was ItemValue which doesnt create a new copy

2023-10-27 00:05 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/common/utils/RegistryValue.java
> +public class RegistryValue<T> {
done in 1f16fa4

2023-10-27 00:15 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/common/utils/ItemValue.java
> +        this(item, item.map(
Lazy loaded using nullable and the getter in 743bc21 - let me know if you meant something else.

2023-10-27 00:15 UTC, sisby-folk commented
Set for review again.

2023-10-27 01:30 UTC, ThatGravyBoat requested changes

2023-10-27 01:30 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/common/utils/ItemValue.java
> +    public static Codec<ItemValue> CODEC = Codec.either(
All static fields should be at the top.

2023-10-27 01:30 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/common/utils/CompatUtils.java
> +        String prettifiedNamespace = StringUtils.capitalize(namespace.replace("_", " ").replace("/", " 🡲 "));
You want to use `WordUtils.capitalizeFully` or else it will only capitalize the first letter so for example for `ad_astra` it would be "Ad astra" instead of "Ad Astra"

2023-10-27 02:01 UTC, sisby-folk commented
Looks like a change has introduced some codec issues and crashing so I've gotta check that out first.

2023-10-27 02:01 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/common/utils/CompatUtils.java
> +        String prettifiedNamespace = StringUtils.capitalize(namespace.replace("_", " ").replace("/", " 🡲 "));
Thank you! done in ac99662

2023-10-27 02:01 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/common/utils/ItemValue.java
> +    public static Codec<ItemValue> CODEC = Codec.either(
sorted in ac99662

2023-10-27 02:12 UTC, sisby-folk commented
Sorted! Accidentally put a `null` where a `t -> null` should've been during either mapping, assuming that was a valid shortcut.

Set for review again!

2023-10-27 15:11 UTC, ThatGravyBoat approved these changes

2023-10-27 15:12 UTC, merged