Tiles the background from a resource image.
terrarium-earth/hercules pull request #125
Opened 2023-11-02 01:49 UTC by SubordinalBlue

The resource file 'header.png' has unused space.
This uses the bottom left 128x128 square of that resource.

Critique: I'd rather this feature respected the alpha channel of the png.

2023-11-02 02:53 UTC, SubordinalBlue commented
After tiling-the-backrgound-*with-alpha*, a fall back enhancement, imho, would be reading a color value _with alpha_ to fill the background with. Currently the background fill color is hard-coded.

2023-11-02 04:02 UTC, SubordinalBlue commented
Fixed to respect/utilize the alpha channel of the source resource.
Hat tip to Herrah. TY.

2023-11-02 04:40 UTC, sisby-folk commented
Looks like it needs a little TLC still.

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/2730a620-6211-4982-a221-bd60bb36049e)

might also want to consider using a different texture for the left pane vs main pane.

you've also got some accidental wacky indentation here and a space missing after a comma:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/7f6c1cbc-603e-494f-aeb2-d94307b8b7cc)

2023-11-02 04:57 UTC, SubordinalBlue commented
Odd, about it not showing anything for you. The updated `heading.png` did go in the second commit.

Good idea about separate background treatment for the side bar; I'll look into that.

Will fix the white-space issues next commit.

2023-11-02 05:08 UTC, SubordinalBlue commented
"Doh" on placing the new `heading.png` in the wrong place.

2023-11-02 05:26 UTC, SubordinalBlue commented
On the matter of treating the side bars (groups and single quest view, and perhaps the edit stuff on the right side)... I see all those widgets subclass AbstractQuestScreen, and weren't overriding to do their own background drawing.

So, perhaps that should be a separate PR. What do you think?

2023-11-02 05:27 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
>              int sidebarWidth = (int) (this.width * 0.25f) - 2;
I reckon it's worth moving textures to give you some more freedom, and then use that freedom to have a seperately drawn sidebar texture.

So just under HEADING, you can add

`public static final ResourceLocation BACKGROUND = new ResourceLocation(Heracles.MOD_ID, "textures/gui/background.png");`

then add that png as a 256x256 and make the top half the transparent black color

and then here, you can just:

```suggestion
        RenderSystem.enableBlend();
        RenderSystem.defaultBlendFunc();
        int sidebarWidth = (int) (this.width * 0.25f) - 2;
        if (drawSidebar()) {
            graphics.blitRepeating(BACKGROUND, 0, 0, sidebarWidth, height, 0, 0, 128, 128);
            graphics.blitRepeating(BACKGROUND, sidebarWidth, 0, width - sidebarWidth, height, 128, 0, 128, 128);
        } else {
            graphics.blitRepeating(BACKGROUND, 0, 0, width, height, 128, 0, 128, 128);
        }
        RenderSystem.disableBlend();
        graphics.blitRepeating(HEADING, 0, 0, this.width, 15, 0, 0, 128, 15);
        if (drawSidebar()) {
```

2023-11-02 05:47 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
>              int sidebarWidth = (int) (this.width * 0.25f) - 2;
thinking about this a bit harder, moving this from header might be wrong.

2023-11-02 10:27 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
>              int sidebarWidth = (int) (this.width * 0.25f) - 2;
Hey hello! I've cooked up a way to theme the header, sidebar, and the seperator between the four sections.

Here's the updated default, and an example customized:

![heading original](https://github.com/terrarium-earth/Heracles/assets/55819817/dff1a4b6-c5ba-4951-98d3-ad2f7f3ddf00)

![heading fancy](https://github.com/terrarium-earth/Heracles/assets/55819817/1a87ee11-a71f-42ed-8424-0f2617c5c41a)

```suggestion
        RenderSystem.enableBlend();
        RenderSystem.defaultBlendFunc();
        if (drawSidebar()) {
            int sidebarWidth = (int) (this.width * 0.25f) - 2;
            graphics.blitRepeating(HEADING, 0, 15, sidebarWidth, height - 15,0, 128, 128, 128); // Side Background
            graphics.blitRepeating(HEADING, sidebarWidth + 2, 15, width - sidebarWidth, height - 15,128, 128, 128, 128); // Main Background
            graphics.blitRepeating(HEADING, 0, 0, sidebarWidth, 15, 0, 0, 128, 15); // Side Header
            graphics.blitRepeating(HEADING, sidebarWidth + 2, 0, width - sidebarWidth, 15, 130, 0, 126, 15); // Main Header
            graphics.blitRepeating(HEADING, sidebarWidth, 0, 2, 15, 128, 0, 2, 15); // Header Separator
            graphics.blitRepeating(HEADING, sidebarWidth, 15, 2, height - 15, 128, 15, 2, 113); // Body Separator
        } else {
            graphics.blitRepeating(HEADING, 15, 0, width, height - 15,128, 128, 128, 128); // Main Background
            graphics.blitRepeating(HEADING, 0, 0, width, 15, 130, 0, 126, 15); // Main Header
        }
        RenderSystem.disableBlend();
        if (false) {
```

2023-11-02 12:17 UTC, SubordinalBlue commented
Looks great to me, your changes. TY!

2023-11-02 14:22 UTC, ThatGravyBoat requested changes

2023-11-02 14:22 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
> +        if (false) {
This if statement should be removed

2023-11-02 21:52 UTC, SubordinalBlue commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
> +        if (false) {
The two statements inside the `if` statement too, or just keep them?

2023-11-03 04:02 UTC, SubordinalBlue commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
> +        if (false) {
Looks like Sisby-folk addressed this.

2023-11-03 05:28 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
> +            WidgetUtils.blitTiling(graphics, HEADING, 15, 0, width, height - 15, 128, 128, 128, 128); // Main Background
15 down, not 15 right!

```suggestion
            WidgetUtils.blitTiling(graphics, HEADING, 0, 15, width, height - 15, 128, 128, 128, 128); // Main Background
```

2023-11-03 05:31 UTC, SubordinalBlue commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
> +        if (false) {
Danke schön!

2023-11-03 06:28 UTC, sisby-folk commented
Looking good for a second round now.

2023-11-03 09:05 UTC, ThatGravyBoat requested changes

2023-11-03 09:05 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/client/WidgetUtils.java
> +    public static void blitTiling(GuiGraphics graphics, ResourceLocation atlasLocation, int targetX, int targetY, int targetWidth, int targetHeight, int sourceX, int sourceY, int sourceWidth, int sou
Widget Utils is meant for common widget code between tasks and rewards so this should be in the client utils

2023-11-03 10:25 UTC, SubordinalBlue commented on common/src/main/java/earth/terrarium/heracles/api/client/WidgetUtils.java
> +    public static void blitTiling(GuiGraphics graphics, ResourceLocation atlasLocation, int targetX, int targetY, int targetWidth, int targetHeight, int sourceX, int sourceY, int sourceWidth, int sou
I this new commit, 499d6c6, did it.

2023-11-04 11:07 UTC, ThatGravyBoat approved these changes

2023-11-04 11:09 UTC, merged