Improve theming with various slice textures
terrarium-earth/hercules pull request #135
Opened 2023-11-08 14:11 UTC by sisby-folk

Addresses most of #134.

![javaw_mmZozlGzqv](https://github.com/terrarium-earth/Heracles/assets/55819817/a8228df5-27b1-4358-b4cc-43ad3e38a458)
![javaw_tj0fKmyQ76](https://github.com/terrarium-earth/Heracles/assets/55819817/4f191fd4-4c5f-4d6a-b604-e347d5d0dac4)

Covers everything except vanilla-style buttons.

Still need to finish AddDisplayWidget as well, but that's in-scope.

2023-11-09 06:26 UTC, sisby-folk commented
Realized the texture for "selected reward widget" made sense alongside the widget background, so I've added that.

Also fixed claim buttons appearing on those widgets, and being able to claim 0 rewards.

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/96ef1d03-59a1-43d5-9fb5-0a3912a22e57)

2023-11-10 03:26 UTC, sisby-folk commented
Add theming for the groups list

https://github.com/terrarium-earth/Heracles/assets/55819817/4f07141e-17c3-4024-8914-fca364e406e8

2023-11-10 03:37 UTC, sisby-folk commented
Added theming for quests view scrollbars

https://github.com/terrarium-earth/Heracles/assets/55819817/91356312-c029-4f32-9742-f3e5ef9b3a24

2023-11-10 03:55 UTC, sisby-folk commented
Added theming for the background for modals (modals themselves were already themeable)

![javaw_DXDtk6xmNL](https://github.com/terrarium-earth/Heracles/assets/55819817/4d5de851-bf7e-4982-8991-d5c0dc55f2b7)
![javaw_t8u4Ig3M45](https://github.com/terrarium-earth/Heracles/assets/55819817/81bf3b9a-8363-4f72-b433-998b82aa3c71)

Also extended the background to cover the header - this avoids strange artifacts with themes that don't have a perfectly square header bar (see above)

2023-11-10 04:14 UTC, sisby-folk commented
Added themeable quest highlight overlays.

![javaw_HLhkI1SNpC](https://github.com/terrarium-earth/Heracles/assets/55819817/e4f21f55-cae8-41ec-9dbd-0732c609db4d)

![javaw_Tho1jrJxqa](https://github.com/terrarium-earth/Heracles/assets/55819817/de445a3a-13a3-47f2-9ce5-d94018cc381a)

These are added to the background textures themselves, so they can match the shape.

2023-11-10 05:17 UTC, sisby-folk commented
Added themeable pinned quests + screen

![javaw_rkmqLX8tBz](https://github.com/terrarium-earth/Heracles/assets/55819817/40d2c0f6-a8f3-4d19-83b9-396348ef79bb)

![javaw_TgvFatCgR6](https://github.com/terrarium-earth/Heracles/assets/55819817/ba952764-a2e3-4a58-b9f3-ffa668c07ba5)

minor uplift in the fake popup on default as well.

2023-11-12 05:06 UTC, sisby-folk commented
Alright, considering there's no activity here and the PR is going to be uncomfortably large no matter what, we've merged in our text recoloring + translatableifying PR as well.

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/4f0a1320-a707-4f8b-a38b-0f520f1103e1)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/45136d3d-657c-462c-80d7-24db3c25467e)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/d5911b5a-43d8-498e-848b-0f81e2fb400d)

2023-11-12 17:11 UTC, ThatGravyBoat commented
So ive taken a look at the color part of the PR and found a few issues and concerns ive made a PR to fix them https://github.com/sisby-folk/Heracles/pull/2 if you can take a look that would be great!

2023-11-13 23:37 UTC, sisby-folk commented
We don't have any plans to tack anything further on this PR btw - merge as soon as you're ready.

2023-11-13 23:56 UTC, ThatGravyBoat commented
ill review in about an hour when if I have time if not tomorrow

2023-11-14 14:33 UTC, ThatGravyBoat requested changes

2023-11-14 14:33 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/widgets/buttons/ThemedButton.java
> +public interface ThemedButton {
I would perfer if this was a class that extended buttons and overrode the methods instead of mixing into button

2023-11-14 14:33 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/widgets/modals/SelectRewardsModal.java
> +        claimButton = ThemedButton.builder(ConstantComponents.Rewards.CLAIM_REWARD, b -> {
addChild returns the type please combine these back to 1 line.

2023-11-14 14:33 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/handlers/QuestTutorial.java
> +                    Heracles.LOGGER.error("[Heracles] Failed to write tutorial", e);
Prefixing is not required as with logger it will print as `[00:00:00] [Render Thread/ERROR] (Heracles) ${message}`

2023-11-14 14:33 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/rewards/client/defaults/XpRewardWidget.java
> +    public boolean isInteractive() {
name the fields `isInteractive` to remove the need for overriding this method in almost every widget

2023-11-14 14:33 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/mixins/client/AbstractButtonMixin.java
> +public abstract class AbstractButtonMixin extends AbstractWidget {
Read comment in ThemeButton

2023-11-14 22:26 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/widgets/buttons/ThemedButton.java
> +public interface ThemedButton {
It mixes into AbstractButtonWidget, and - We tried this at first, but solving the problem this way got very complicated very fast. Consider how I might implement the theme onto `SelectableImageButton` (extends ImageButton extends Button) vs `SelectableTabButton` (extends AbstractButton)

2023-11-14 22:27 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/handlers/QuestTutorial.java
> +                    Heracles.LOGGER.error("[Heracles] Failed to write tutorial", e);
Isn't that only true in a dev environment?

2023-11-14 22:35 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/widgets/modals/SelectRewardsModal.java
> +        claimButton = ThemedButton.builder(ConstantComponents.Rewards.CLAIM_REWARD, b -> {
done in 10efdf3

2023-11-14 22:36 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/rewards/client/defaults/XpRewardWidget.java
> +    public boolean isInteractive() {
(forgets how records work) didn't know that trick! - done in 10efdf3

2023-11-14 23:31 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/handlers/QuestTutorial.java
> +                    Heracles.LOGGER.error("[Heracles] Failed to write tutorial", e);
no it also shows in prod, in prod it actually shows as `[00:00:00] [Render thread/INFO] [ea.te.he.Heracles/]: ${message}`

2023-11-15 06:44 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/handlers/QuestTutorial.java
> +                    Heracles.LOGGER.error("[Heracles] Failed to write tutorial", e);
(latest.log)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/dce761c9-5d72-4254-9165-e1dce42abaec)

2023-11-15 08:28 UTC, sisby-folk commented
Heya @ThatGravyBoat - I've got some further stuff on the colours that I think need looking at but I can't go about.

I've readded the json default pack-in json file, but it needs to be fixed to the new keys and value formats if they've changed (#FFFFFF format would probably be best) - I think we've gotta include it to be in-line with the other respackable stuff in terms of how intuitive it is to replace. 

I also think that considering there's a fancier system for loading the json now, it's worth considering having the defaults stored in json purely instead of in code - this would prevent accidentally adding it to one but not the other. However it's probably more critical to ensure that respacks can partially override text colours while falling back on defaults (this happens as-is, right?) - otherwise Heracles updates could fail on old respacks.

2023-11-15 12:31 UTC, ThatGravyBoat commented
There is no need for the JSON as if the data is missing in the JSON it will default back to the value that is in code even if its only 1 line, this also works for old resourcepacks as it will default.

2023-11-15 12:31 UTC, ThatGravyBoat commented
pack developers would only need to add the elements they need not all, so if they only change the group name they only need to add group data the rest gets used from code

2023-11-15 13:40 UTC, sisby-folk commented
Ah okay that's good - feel free to remove the json then. Would you be able to send us through the new format using the colours from this pack? 
[Heracles_Paper__Ribbon.zip](https://github.com/terrarium-earth/Heracles/files/13365388/Heracles_Paper__Ribbon.zip)

2023-11-15 23:53 UTC, sisby-folk commented
Ignore me, got around to it - here's the sample pack.

[[Heracles] Paper & Ribbon.zip](https://github.com/terrarium-earth/Heracles/files/13370795/Heracles.Paper.Ribbon.zip)

Theme json is removed as well so this is ready for re-review.

2023-11-16 12:37 UTC, ThatGravyBoat requested changes

2023-11-16 12:37 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/mixins/client/AbstractButtonMixin.java
> +    public void applyThemedTexture(Args args) {
prefix your mixin methods with `heracles$`.

2023-11-16 12:52 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/mixins/client/AbstractButtonMixin.java
> +    public void applyThemedTexture(Args args) {
added!

2023-11-18 09:09 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/handlers/QuestTutorial.java
> +                    Heracles.LOGGER.error("[Heracles] Failed to write tutorial", e);
I've gone ahead and made this change consistent in d0f5138 - i figure this will make it easier to go one way or the other.

2023-11-20 00:22 UTC, ThatGravyBoat approved these changes

2023-11-20 00:50 UTC, merged