Center document widget and top bar title together
terrarium-earth/hercules pull request #147
Opened 2023-12-03 02:53 UTC by SubordinalBlue

Just two commits so far, with commentary in each: first to clean up a tad; second to get centering math in agreement for both the DocumentWidget and the top bar title.

There is an issue, existing before this patch, of duplication of the logic for positioning the Hermes' DocumentWidget; addressing that remains for a further commit.

I wanted to open this PR now both both for feedback on the centering changes and, to be open to advice on how to address the duplicated code.

2023-12-03 03:09 UTC, SubordinalBlue commented
## Test images.
All are details from F2 screenshots inside a graphics editor to over-lay guide lines, etc.

Full width view, top portion of a quest screen with sidebar. The editor-added green boxes have equal pixel width (UI=4).
<img width="1473" alt="image" src="https://github.com/terrarium-earth/Heracles/assets/6677700/934d855d-f8b5-4e11-817c-055bca3264ca">

Tighter details, same layout, at different UI scales `5` to `1`:
 5 | 4 | 3 | 2 | 1       
---|---|---|---|---
<img width="86" alt="image" src="https://github.com/terrarium-earth/Heracles/assets/6677700/1c412169-760f-4405-a474-2e565f4626a4">|<img width="68" alt="image" src="https://github.com/terrarium-earth/Heracles/assets/6677700/776d6723-6bc5-488c-9011-01a18e2a90e8">|<img width="62" alt="image" src="https://github.com/terrarium-earth/Heracles/assets/6677700/d5c46f24-0196-4166-9357-537f84e706df">|<img width="108" alt="image" src="https://github.com/terrarium-earth/Heracles/assets/6677700/96b0e317-5613-46d1-a2ee-07d9c9687f35">|<img width="31" alt="image" src="https://github.com/terrarium-earth/Heracles/assets/6677700/0e2a4e6c-1e4f-4444-a0c6-63cce3262960">

Details for the no-side-bar case look the same, with the guide line being at 960px on a 1920px-wide MC screen.

2023-12-03 06:00 UTC, SubordinalBlue commented
Added two further commits:
- eb36683 for edits that shouldn't have "escaped" the previous commit, my bad.
- 95c5527 for consolidating duplicated content area calculations.

Further details in those commits' messages.

2023-12-13 11:44 UTC, ThatGravyBoat requested changes

2023-12-13 11:44 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
> +    protected static int SIDE_BAR_WIDTH;
should be lowercase since its not a constant

2023-12-13 12:22 UTC, SubordinalBlue commented on common/src/main/java/earth/terrarium/heracles/client/screens/AbstractQuestScreen.java
> +    protected static int SIDE_BAR_WIDTH;
Good catch. Fixed in a64366c

2023-12-13 18:28 UTC, ThatGravyBoat approved these changes

2023-12-13 18:28 UTC, ThatGravyBoat commented
After conflict is fixed it can be merged 👍

2023-12-13 22:36 UTC, SubordinalBlue commented
Fixed.

2023-12-14 22:49 UTC, merged