Reformat task and reward titles/descriptions.
terrarium-earth/hercules pull request #76
Opened 2023-09-26 10:18 UTC by sisby-folk

Addresses #75 - most edits are covered there, though some small adaptations were made to better fit what's in the code.

Some later-refactorable oddities are included - including switching the title and description in code instead of in language keys (bad) - this is due to TaskTitleFormatter being the way that it is. It could be removed to resolve this, or just these specific formatters.

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/84a51567-dee0-47ab-af48-d66974310f0c)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/0de45813-7546-49fd-b6e1-6104dd7893dc)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/9ab867a5-245b-4a44-8e91-8699e46bba27)

2023-09-27 07:55 UTC, ThatGravyBoat requested changes

2023-09-27 07:55 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/screens/quest/tasks/TaskListHeadingWidget.java
> +public record TaskListHeadingWidget(float completion, java.util.Map<String,earth.terrarium.heracles.common.utils.ModUtils.QuestStatus> quests) implements DisplayWidget {
fully qualified names should be avoided and imports should be used.

2023-09-27 07:55 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/ItemTaskWidget.java
> +        String title = task.collectionType() == GatherItemTask.CollectionType.AUTOMATIC ? (task.item().isTag() ? TITLE_TAG : TITLE_ITEM) : (task.item().isTag() ? TITLE_SUBMIT_TAG : TITLE_SUBMIT_ITEM)
These are very poor for readability, I would suggest putting these into a method and using if statements as 3 ternary operators make this a lot harder to read even with the parentheses.

2023-09-27 07:55 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/display/TaskTitleFormatters.java
> -        TaskTitleFormatter.register(GatherItemTask.TYPE, (task) -> Component.translatable(toTranslationKey(task, task.target() == 1), task.item().getDisplayName(Item::getDescription)));
Task titles are used for the objective display so removing this will make it so that they do not show up in that display.

2023-09-27 21:37 UTC, acikek commented on common/src/main/resources/assets/heracles_tasks/lang/en_us.json
> +    "task.heracles.advancement.desc.plural": "%s Achieve one of the following",
See my comment on the issue [here](https://github.com/terrarium-earth/Heracles/issues/75#issuecomment-1736638636)

2023-09-28 06:37 UTC, sisby-folk commented on common/src/main/resources/assets/heracles_tasks/lang/en_us.json
> +    "task.heracles.advancement.desc.plural": "%s Achieve one of the following",
We have a lack of opinon on this bc a lot of these adds-nothing repetitive title/desc combos should just be title-only tbh. You've only explained this as something you wouldn't do, so i'm happy for a maintainer to +1 that thought or change it themselves if desired.

2023-09-28 06:41 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/display/TaskTitleFormatters.java
> -        TaskTitleFormatter.register(GatherItemTask.TYPE, (task) -> Component.translatable(toTranslationKey(task, task.target() == 1), task.item().getDisplayName(Item::getDescription)));
Ten four! Restored along with their lang keys in a9e9319

2023-09-28 06:42 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/ItemTaskWidget.java
> +        String title = task.collectionType() == GatherItemTask.CollectionType.AUTOMATIC ? (task.item().isTag() ? TITLE_TAG : TITLE_ITEM) : (task.item().isTag() ? TITLE_SUBMIT_TAG : TITLE_SUBMIT_ITEM)
Done up into a nested if-else static method in a9e9319

2023-09-28 06:42 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/screens/quest/tasks/TaskListHeadingWidget.java
> +public record TaskListHeadingWidget(float completion, java.util.Map<String,earth.terrarium.heracles.common.utils.ModUtils.QuestStatus> quests) implements DisplayWidget {
Oop! Must be IDE jank, sorted in a9e9319

2023-09-28 07:05 UTC, sisby-folk commented
Pins!

Release:
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/a3faaeac-5c62-4ae5-abaa-cd8dafc9fb23)
PR:
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/fdc35197-eb4f-466f-a073-413aa932312f)

Judging from this, pinned quests should eventually use a third formating that's different to title or description (see 'complete an advancement'), but that falls outside of the scope i'm comfortable with in this PR.

2023-09-28 07:34 UTC, ThatGravyBoat commented on common/src/main/resources/assets/heracles_tasks/lang/en_us.json
> +    "task.heracles.advancement.desc.plural": "%s Achieve one of the following",
I would agree that "achieve" is redundant in this situation and should likely be "complete" or another word to describe the action being done.

2023-09-28 07:36 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/screens/quest/tasks/TaskListHeadingWidget.java
> +public record TaskListHeadingWidget(float completion, java.util.Map<String,earth.terrarium.heracles.common.utils.ModUtils.QuestStatus> quests) implements DisplayWidget {
You seemed to of missed the `java.util.Map` in your fix

2023-09-28 08:00 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/screens/quest/tasks/TaskListHeadingWidget.java
> +public record TaskListHeadingWidget(float completion, java.util.Map<String,earth.terrarium.heracles.common.utils.ModUtils.QuestStatus> quests) implements DisplayWidget {
Ah thanks, got that in 9ac8128

2023-09-28 08:00 UTC, sisby-folk commented on common/src/main/resources/assets/heracles_tasks/lang/en_us.json
> +    "task.heracles.advancement.desc.plural": "%s Achieve one of the following",
Swapped to complete in 9ac8128

2023-10-01 15:30 UTC, merged