Translate CollectionType
terrarium-earth/hercules pull request #83
Opened 2023-10-03 09:02 UTC by sisby-folk

Further Addresses #75

Makes collection type translatable, and translates it in english to acquire/submit/auto-submit.

Also fixes the setting keys.

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/7a1f86a3-f6bf-4513-a1ba-28cf37f954f5)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/6dcf4575-cd76-4cb9-a1a8-1d6f8ca0a0c3)

2023-10-03 13:41 UTC, ThatGravyBoat requested changes

2023-10-03 13:41 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/CollectionType.java
> +        return "gui.heracles.tasks.collection_type.%s".formatted(name().toLowerCase());
Okay I know this wasn't done before because it was used directly for display but using `.toLowerCase()` can cause unintended things, `.toLowerCase(Locale.ROOT)` should be used instead as the one without locale uses system lang and in some languages English letters when lowercased change completely such as Turkish where lowercase "I" is a dotless I

2023-10-03 13:41 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/widgets/buttons/EnumButton.java
> +        return Component.translatable(this.value.getSerializedName(), this.value.name().charAt(0) + this.value.name().substring(1).toLowerCase());
This one is shouldn't use locale like I said for the enum for lowercase as if it does fail we at least want to go with the system language specified lowercasing.

2023-10-03 22:55 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/tasks/CollectionType.java
> +        return "gui.heracles.tasks.collection_type.%s".formatted(name().toLowerCase());
Used locale here in 4c13416

2023-10-03 22:55 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/widgets/buttons/EnumButton.java
> +        return Component.translatable(this.value.getSerializedName(), this.value.name().charAt(0) + this.value.name().substring(1).toLowerCase());
Did absolutely nothing here in 4c13416

2023-10-04 11:18 UTC, ThatGravyBoat approved these changes

2023-10-04 11:18 UTC, merged