Improve GatherTask Reliability
terrarium-earth/hercules pull request #84
Opened 2023-10-03 12:52 UTC by sisby-folk

Closes #67

Detect SlotChanged-based inventory updates using an injected interface 
Allow for partial progress updates

https://github.com/terrarium-earth/Heracles/assets/55819817/890ba3ef-4f67-4625-b5c0-9ba6dc70f288

picking up, partial picking up, and inventory transfers now work. For whatever strange reason `/give` doesn't, even though I can see it using add. 

The original addItem mixin was at return, but the `stack` parameter is actually cleared before return in a lot of code paths, so it's gotta be head-only. I guess if the player _tries_ to get something in their inventory and fails, it's still worth checking.

2023-10-03 13:48 UTC, ThatGravyBoat requested changes

2023-10-03 13:48 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/mixins/common/InventoryMixin.java
> +        heracles$addedStack = stack.copy();
Wouldn't this copy mean that consuming actions wouldn't consume?

2023-10-03 22:57 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/mixins/common/InventoryMixin.java
> +        heracles$addedStack = stack.copy();
Thankfully not! This should explain it right quick - that stack never even gets passed down past the initial check (and rightfully! we need to check the whole inventory anyway)
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/7af589d5-4798-44c0-89aa-2709ee15d1d0)

2023-10-04 11:20 UTC, ThatGravyBoat approved these changes

2023-10-04 11:20 UTC, merged