Add Custom Task/Reward Titles and Icons
terrarium-earth/hercules pull request #86
Opened 2023-10-04 08:03 UTC by sisby-folk

Closes #65

🐉 Yea we're like 1/3 as confident going through this as the last howevermany - so this'll be a slow rolling draft 

Starting with the gather task as a PoC - Task title is basically mint as-is, but icon needs some work.

https://github.com/terrarium-earth/Heracles/assets/55819817/133a66b5-9d26-4986-a9c2-9014b9a670e8

To do:

- Use the actual item translation key on the icon button.
- Make the icon value optional and the setting button clearable, and default to empty (or use AIR to represent this, adding a boolean method to QuestIcon to return presence).
- Generify this mess to all task and reward types without weighing everything the hell down (they're records so, uh, might not be fully possible)

2023-10-05 01:01 UTC, sisby-folk commented
Working much nicer now. Only needs to be applied to all types now which is kind of scary prospect.

Just putting these values on all tasks and reward types like I have for gather is entirely viable, but i'll admit it feels like a mess. Then again, they all have duplicate code for rendering item icons, so why not! I'll see if I can do any better than that afterwards.

https://github.com/terrarium-earth/Heracles/assets/55819817/b6883d95-90aa-441a-8d3f-c0000d72fa1a

2023-10-05 06:02 UTC, sisby-folk commented
This one should be ready - all task and reward types that had registered settings have title and icon overrides now. That only leaves out the technical or data-only types - locationtask, compositetask, and selectablereward.

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/4fbbccef-0248-427e-a2ed-9549ae685b68)

2023-10-05 07:24 UTC, ThatGravyBoat requested changes

2023-10-05 07:24 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/defaults/DummyTask.java
> +                QuestIcons.CODEC.fieldOf("icon").orElse(new ItemQuestIcon(Items.AIR)).forGetter(DummyTask::icon),
A new codec should be made for QuestIcons to default back to ItemQuestIcon if the input value is a ResourceLocation as right now this is a breaking change and means that any dummy quests with an icon set will be reset to a barrier.

2023-10-05 07:24 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/XpTaskWidget.java
> +            WidgetUtils.drawItemIcon(graphics, Items.EXPERIENCE_BOTTLE.getDefaultInstance(), x, y, iconSize);
I think with how often this is done 2 methods that take a QuestIcon with drawItemIcon and drawItemIconWithTooltip that does the visibility check would be good.

2023-10-05 07:24 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/XpTaskWidget.java
> +            !task.title().isEmpty() ? Component.translatable(task.title()) : TaskTitleFormatter.create(this.task), x + iconSize + 16, y + 6, 0xFFFFFFFF,
For this one a method that just takes the customizable task and makes the title would be good as you also do this a lot.

2023-10-05 07:24 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/quests/defaults/ItemQuestIcon.java
> +        return item != null && item != Items.AIR;
I would perfer instead of `!=` for the item comparison that `item.is` is used as to future proof.

2023-10-05 07:24 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/quests/QuestIcon.java
> +    boolean isVisible();
I would say default this to `true` as in the future not many icon types will use this and will always likely set to true

2023-10-05 07:30 UTC, sleepingdragoninn commented on common/src/main/java/earth/terrarium/heracles/api/tasks/defaults/DummyTask.java
> +                QuestIcons.CODEC.fieldOf("icon").orElse(new ItemQuestIcon(Items.AIR)).forGetter(DummyTask::icon),
I'm not exactly sure how to achieve that behaviour - we've only just started working with codecs.

2023-10-05 08:21 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/quests/defaults/ItemQuestIcon.java
> +        return item != null && item != Items.AIR;
I'm not familiar with any method called `is()` on item - which one of us is confused?

2023-10-05 08:22 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/quests/QuestIcon.java
> +    boolean isVisible();
Sorted in e2bdf4d!

2023-10-05 08:23 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/XpTaskWidget.java
> +            !task.title().isEmpty() ? Component.translatable(task.title()) : TaskTitleFormatter.create(this.task), x + iconSize + 16, y + 6, 0xFFFFFFFF,
Sorted in e2bdf4d! three methods, `renderOverride` that returns true if it rendered (for non-items), and the two item rendering types.

2023-10-05 08:23 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/tasks/client/defaults/XpTaskWidget.java
> +            WidgetUtils.drawItemIcon(graphics, Items.EXPERIENCE_BOTTLE.getDefaultInstance(), x, y, iconSize);
Sorted in e2bdf4d! three methods, `renderOverride` that returns true if it rendered (for non-items), and the two item rendering types.

2023-10-05 08:32 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/quests/defaults/ItemQuestIcon.java
> +        return item != null && item != Items.AIR;
Sorry I meant `equals` `is` is only on the `ItemStack`

2023-10-05 09:44 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/quests/defaults/ItemQuestIcon.java
> +        return item != null && item != Items.AIR;
there is not an itemstack in this expression at all, there are two items, one is constant - am I missing something?

2023-10-05 15:52 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/quests/defaults/ItemQuestIcon.java
> +        return item != null && item != Items.AIR;
What I meant is my bad about the `is` method as I realized that it was only on the `ItemStack` here you should be using `!Items.AIR.equals(item)` instead of `!=`

```suggestion
        return item != null && !Items.AIR.equals(item);
```

2023-10-05 15:55 UTC, MsRandom commented on common/src/main/java/earth/terrarium/heracles/api/quests/defaults/ItemQuestIcon.java
> +        return item != null && item != Items.AIR;
This doesn't make a difference as it's a reference check regardless, however you can also do `Object.equals(item, AIR)` and remove the null check entirely.

2023-10-05 15:57 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/api/tasks/defaults/DummyTask.java
> +                QuestIcons.CODEC.fieldOf("icon").orElse(new ItemQuestIcon(Items.AIR)).forGetter(DummyTask::icon),
Here this is the codec for it

```java
    private static final Codec<QuestIcon<?>> LEGACY_ICON_CODEC = BuiltInRegistries.ITEM.byNameCodec()
        .xmap(ItemQuestIcon::new, icon -> icon instanceof ItemQuestIcon itemIcon ? itemIcon.item() : Items.BARRIER);
    private static final Codec<QuestIcon<?>> DUMMY_TASK_ICON_CODEC = CodecExtras.eitherLeft(Codec.either(QuestIcons.CODEC, LEGACY_ICON_CODEC));
```

2023-10-05 23:26 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/quests/defaults/ItemQuestIcon.java
> +        return item != null && item != Items.AIR;
uh, can't we not do that considering it's an inequality check?

2023-10-05 23:27 UTC, MsRandom commented on common/src/main/java/earth/terrarium/heracles/api/quests/defaults/ItemQuestIcon.java
> +        return item != null && item != Items.AIR;
Oh true, my bad.

2023-10-05 23:28 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/tasks/defaults/DummyTask.java
> +                QuestIcons.CODEC.fieldOf("icon").orElse(new ItemQuestIcon(Items.AIR)).forGetter(DummyTask::icon),
Added to dummytask! 
c045875

2023-10-05 23:35 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/api/quests/defaults/ItemQuestIcon.java
> +        return item != null && item != Items.AIR;
We've factored out `isVisible` and made `render` just always return boolean, which simplifies things a bit - this null / non-air check exists at the top of ItemQuestIcon.render now.

2023-10-06 04:23 UTC, sisby-folk commented
things to fix i noticed today: toasts are broken! 

also locationtask needs its stuff updated to match the new dummy codec.

2023-10-06 13:43 UTC, sisby-folk commented
I believe we're dusted! feel free to check it 
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/c8e88382-71ab-4cdb-990d-5500c7837604)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/9835bac2-296d-41b5-b912-f6b641eca37a)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/ceb3c197-aa40-472e-8e36-d6a868c83f70)

2023-10-06 14:21 UTC, ThatGravyBoat approved these changes

2023-10-07 12:31 UTC, ThatGravyBoat approved these changes

2023-10-07 12:32 UTC, merged