Add individual reward claiming
terrarium-earth/hercules pull request #92
Opened 2023-10-08 02:07 UTC by sisby-folk

Addresses a small point in #68 

Adds the loot bag button to all reward types, instead of just selectable. Adds a new packet to handle claiming a single reward, and a method in quest to help out.

The code added to widgets is repetitive as hell - I wasn't sure whether it was appropriate to interface out, and if so in what format - feel free to let us know.

https://github.com/terrarium-earth/Heracles/assets/55819817/73dd31e0-2b6f-4aa2-a4e0-1e42ae811c64

Closing and reopening the screen is required bc of #68 which is slightly-too-large-a-refactor for us to do, but we would love someone else to pick up, considering how much it would polish a lot of our recent contributions.

2023-10-08 02:15 UTC, sisby-folk commented
Here's another shot showing the individual claiming better

https://github.com/terrarium-earth/Heracles/assets/55819817/f93bcfd0-a5c3-425e-be97-9f9b857c21a2

The screen closing here isn't actually required, I'm just showing the chat.

2023-10-20 17:22 UTC, ThatGravyBoat requested changes

2023-10-20 17:22 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/Heracles.java
> +    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);
Please use the Mojang method `LogUtils.getLogger()` instead

2023-10-20 17:22 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/common/network/packets/rewards/ClaimRewardPacket.java
> +public record ClaimRewardPacket(String quest, String reward) implements Packet<ClaimRewardPacket> {
I would perfer if this is combined with the ClaimRewardsPacket and have the reward string be optional and if its present just claim that reward if its not claim all

2023-10-21 11:14 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/common/network/packets/rewards/ClaimRewardPacket.java
> +public record ClaimRewardPacket(String quest, String reward) implements Packet<ClaimRewardPacket> {
done up using a blank string in 2a725e9 - I didn't wanna mix nulls and empty strings in the buffer, but if you have a better way to do it let me know.

2023-10-21 11:14 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/Heracles.java
> +    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);
done in 2a725e9

2023-10-21 20:23 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/common/network/packets/rewards/ClaimRewardPacket.java
> +public record ClaimRewardPacket(String quest, String reward) implements Packet<ClaimRewardPacket> {
An empty string works perfectly fine

2023-10-21 20:24 UTC, ThatGravyBoat approved these changes

2023-10-21 20:24 UTC, merged