Update quest screen when client affects task or reward progress
terrarium-earth/hercules pull request #93
Opened 2023-10-09 06:34 UTC by sisby-folk

closes #68 

Adds systems by which the QuestScreens (QuestScreen and QuestEditScreen) can be updated with new progress, along with relevant packets, helpers, etc. Uses this for checkbox task completion, and the types of reward claiming.

Modelled off of the way pinned quests does it, adapted for use.

PR branch is built off #92 so it'll be a mess until that's merged - just look at the specific commit. Just wanted something to do in the meantime :P

https://github.com/terrarium-earth/Heracles/assets/55819817/ab21f0a1-d1af-484f-87b7-d2370ff5db98

2023-10-22 02:39 UTC, sisby-folk commented
Force pushed this to clean it up - should be good now!

2023-10-22 15:20 UTC, ThatGravyBoat requested changes

2023-10-22 15:20 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/Heracles.java
> +    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);
Please use LogUtils.getLogger()

2023-10-22 15:20 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/common/network/packets/quests/SyncQuestProgressPacket.java
> +                if (Minecraft.getInstance().screen instanceof BaseQuestScreen screen) {
Test this on a server because I dont remember if this will crash or not

2023-10-22 15:20 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/screens/quest/tasks/TaskListWidget.java
> +        this.widgets.add(new MutablePair<>(null, new TaskListHeadingWidget(this.entry.value().tasks().size(), (int) entry.value().tasks().values().stream().filter(t -> progress.getTask(t).isComplete(
this is extremely long cut it down a bit by saving `this.entry.value().tasks()` as a variable

2023-10-22 15:20 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/client/screens/quest/BaseQuestScreen.java
> +        return content.progress().isComplete() ? Component.literal("✔ ").append(super.getTitle()).append(Component.literal(" ✔")) : super.getTitle();
I think that instead of appending this should be a translation like `✔ %s ✔` just in-case someone wants to change it

2023-10-22 15:22 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/heracles/Heracles.java
> +    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);
Ignore this, this was before the force push

2023-10-23 00:26 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/screens/quest/BaseQuestScreen.java
> +        return content.progress().isComplete() ? Component.literal("✔ ").append(super.getTitle()).append(Component.literal(" ✔")) : super.getTitle();
Didn't think of that - that makes sense. Done up in 1f74e6e

2023-10-23 00:26 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/client/screens/quest/tasks/TaskListWidget.java
> +        this.widgets.add(new MutablePair<>(null, new TaskListHeadingWidget(this.entry.value().tasks().size(), (int) entry.value().tasks().values().stream().filter(t -> progress.getTask(t).isComplete(
reused the `tasks` parameter that i forgot about in 1f74e6e

2023-10-23 00:26 UTC, sisby-folk commented on common/src/main/java/earth/terrarium/heracles/common/network/packets/quests/SyncQuestProgressPacket.java
> +                if (Minecraft.getInstance().screen instanceof BaseQuestScreen screen) {
Can confirm works fine on server - been playtesting at home.

2023-10-27 00:15 UTC, sisby-folk commented
Set for review again.

2023-10-27 01:31 UTC, ThatGravyBoat approved these changes

2023-10-28 14:37 UTC, merged