Apply overscroll to quest screen widgets
terrarium-earth/hercules pull request #96
Opened 2023-10-13 00:05 UTC by sisby-folk

Closes #94

https://github.com/terrarium-earth/Heracles/assets/55819817/6f9a595a-fbcb-4c74-bd24-0c99116ce17c

Works great - need to merge the other two first though, or it'll be a mess. Again just read the final commit if desired.

Drafted because this PR also requries a new hermes version to be published and then bumped in this branch. I just did it locally.

2023-10-29 00:02 UTC, sisby-folk commented
Rebased and ready for the hermes release now! I've guessed it as being `1.2.1` and added it to my local, but if it gets released as `1.3.0` just let me know or adjust it in properties yourself.

Feel free to review as well.

2023-11-01 08:32 UTC, ThatGravyBoat requested changes

2023-11-01 08:32 UTC, ThatGravyBoat commented on build.gradle.kts
> +        mavenLocal()
It is now published this can be removed

2023-11-01 08:32 UTC, ThatGravyBoat commented on forge/build.gradle.kts
> +    compileOnly("com.teamresourceful:yabn:1.0.3")
These should be merged now just pull upstream

2023-11-01 10:38 UTC, sisby-folk commented on forge/build.gradle.kts
> +    compileOnly("com.teamresourceful:yabn:1.0.3")
done! 2662665

2023-11-01 10:38 UTC, sisby-folk commented on build.gradle.kts
> +        mavenLocal()
sorted! ecff389

2023-11-02 00:15 UTC, sisby-folk commented
Ready again

2023-11-02 00:57 UTC, ThatGravyBoat approved these changes

2023-11-02 00:57 UTC, merged