Centre quests screen on open, use fixed-size scrollbars
terrarium-earth/hercules pull request #97
Opened 2023-10-14 03:48 UTC by sisby-folk

https://github.com/terrarium-earth/Heracles/assets/55819817/c8da8e80-cc73-4815-a33f-571c5f8e0280

Offset always starts at the dead centre of the allowed offset values. This is a good happy medium between using 0,0 and attempting to perform a more advanced heuristic on quest types.

As the editor improves, making this configurable so that modpack devs can use 0,0 again would make sense - but right now without grid snapping or being able to offset the positions of an entire group, this makes sense I think.

Also the scrollbars were busted before I touched anything, so i went in and rewrote them as fixed-width ones, as that's what i'm familiar with.

2023-10-15 02:45 UTC, ThatGravyBoat requested changes
I think the scrollbar length are a little big maybe half the horizontal one atleast I also think the vertical one could maybe be reduced to about 75%

2023-10-15 03:01 UTC, sisby-folk commented
The scrollbar size currently reflects the actual ratio between screen size and canvas size, meaning it maps to moving the screen across the canvas 1:1

I can change it, but I think I need an alternative to be more explicitly defined - I'm less familiar with "fake scrollbars" that don't have this property.

2023-10-15 03:30 UTC, sisby-folk commented
Here is a video that better explains what I mean: 

https://github.com/terrarium-earth/Heracles/assets/55819817/1cb9ff58-7f15-4122-84a8-e5d9104d4df6

Here, you can see that a scrollbar travelling one of its own lengths is equivalent to the screen being panned by its entire length as in that dimension as well. Also, that the scrollbars clearly indicate how large the edit mode canvas is.

2023-10-17 11:22 UTC, ThatGravyBoat approved these changes
Looks good then

2023-10-17 11:23 UTC, merged